### PR TITLE
window-list: Render thumbnails as cairo surfaces

### LINKED ISSUE #1166: Window List Quit Unexpectedly when hovering
#### Expected behaviour
Window List not crash when hovering over it.

#### Actual behaviour
It crashes.

#### Steps to reproduce the behaviour
Add window list widget to a panel, and mouse over (usually) this will cause it to crash.

#### MATE general version
```
$ mate-session --version
1.24.1
```
#### Package version
local/cairo 1.17.4-1
local/cairo-perl 1.107-2
local/cairomm 1.12.2-4
local/goocanvas 2.0.4-7
local/lib32-cairo 1.17.4-1
local/pango 1:1.48.0-1
local/pixman 0.40.0-1
local/python-cairo 1.20.0-3
local/python2-cairo 1.18.2-4
local/mate-applets 1.24.1-1 (mate-extra)
local/mate-backgrounds 1.24.1-1 (mate)
local/mate-calc 1.24.1-1 (mate-extra)
local/mate-control-center 1.24.1-1 (mate)
local/mate-desktop 1.24.1-1 (mate)
local/mate-icon-theme 1.24.0-1 (mate)
local/mate-icon-theme-faenza 1.20.0-2 (mate-extra)
local/mate-media 1.24.1-1 (mate-extra)
local/mate-menus 1.24.1-1 (mate)
local/mate-netbook 1.24.0-1 (mate-extra)
local/mate-notification-daemon 1.24.1-1 (mate)
local/mate-panel 1.24.1-1 (mate)
local/mate-polkit 1.24.0-1 (mate)
local/mate-power-manager 1.24.1-1 (mate-extra)
local/mate-screensaver 1.24.1-1 (mate-extra)
local/mate-sensors-applet 1.24.1-1 (mate-extra)
local/mate-session-manager 1.24.1-1 (mate)
local/mate-settings-daemon 1.24.1-1 (mate)
local/mate-system-monitor 1.24.0-1 (mate-extra)
local/mate-terminal 1.24.1-1 (mate-extra)
local/mate-themes 3.22.21-1 (mate)
local/mate-user-guide 1.24.0-1 (mate)
local/mate-user-share 1.24.0-1 (mate-extra)
local/mate-utils 1.24.0-1 (mate-extra)

#### Linux Distribution
Archlinux `pacman -Syu` today

#### Link to downstream report of your Distribution
? I don't know what this is tbh

#### Journal log
`mate-session --debug`
```
Dec 02 16:11:35 Hannah org.mate.panel.applet.WnckletFactory[7710]: wnck-applet: ../cairo/src/cairo-surface.c:1733: cairo_surface_mark_dirty_rectangle: Assertion `! _cairo_surface_has_snapshots (surface)' failed.
Dec 02 16:11:35 Hannah audit[7710]: ANOM_ABEND auid=1000 uid=1000 gid=1000 ses=2 pid=7710 comm="wnck-applet" exe="/usr/lib/mate-panel/wnck-applet" sig=6 res=1
Dec 02 16:11:35 Hannah kernel: audit: type=1701 audit(1606954295.638:352): auid=1000 uid=1000 gid=1000 ses=2 pid=7710 comm="wnck-applet" exe="/usr/lib/mate-panel/wnck-applet" sig=6 res=1
Dec 02 16:11:35 Hannah audit: BPF prog-id=58 op=LOAD
Dec 02 16:11:35 Hannah audit: BPF prog-id=59 op=LOAD
Dec 02 16:11:35 Hannah systemd[1]: Started Process Core Dump (PID 9133/UID 0).
Dec 02 16:11:35 Hannah audit[1]: SERVICE_START pid=1 uid=0 auid=4294967295 ses=4294967295 msg='unit=systemd-coredump@15-9133-0 comm="systemd" exe="/usr/lib/systemd/systemd" hostname=? addr=? terminal=? res=success'
Dec 02 16:11:35 Hannah audit[9134]: NETFILTER_CFG table=filter family=7 entries=0 op=xt_register pid=9134 comm="(coredump)"
Dec 02 16:11:35 Hannah kernel: audit: type=1334 audit(1606954295.648:353): prog-id=58 op=LOAD
Dec 02 16:11:35 Hannah kernel: audit: type=1334 audit(1606954295.648:354): prog-id=59 op=LOAD
Dec 02 16:11:35 Hannah kernel: audit: type=1130 audit(1606954295.648:355): pid=1 uid=0 auid=4294967295 ses=4294967295 msg='unit=systemd-coredump@15-9133-0 comm="systemd" exe="/usr/lib/systemd/systemd" hostname=? addr=? terminal=? res=success'
Dec 02 16:11:35 Hannah kernel: audit: type=1325 audit(1606954295.648:356): table=filter family=7 entries=0 op=xt_register pid=9134 comm="(coredump)"
Dec 02 16:11:36 Hannah systemd-coredump[9134]: Process 7710 (wnck-applet) of user 1000 dumped core.
                 
                 Stack trace of thread 7710:
                 #0  0x00007ff31d7ad615 raise (libc.so.6 + 0x3d615)
                 #1  0x00007ff31d796862 abort (libc.so.6 + 0x26862)
                 #2  0x00007ff31d796747 __assert_fail_base.cold (libc.so.6 + 0x26747)
                 #3  0x00007ff31d7a5bf6 __assert_fail (libc.so.6 + 0x35bf6)
                 #4  0x00007ff31dd20cdf cairo_surface_mark_dirty_rectangle (libcairo.so.2 + 0x68cdf)
                 #5  0x00007ff31dd490d0 n/a (libcairo.so.2 + 0x910d0)
                 #6  0x00007ff31dd20c39 cairo_surface_mark_dirty_rectangle (libcairo.so.2 + 0x68c39)
                 #7  0x00007ff31dd21255 cairo_surface_mark_dirty (libcairo.so.2 + 0x69255)
                 #8  0x00007ff31de384ad gdk_pixbuf_get_from_window (libgdk-3.so.0 + 0x404ad)
                 #9  0x000055a33ab0091a n/a (wnck-applet + 0x791a)
                 #10 0x00007ff31da8971d g_cclosure_marshal_VOID__POINTERv (libgobject-2.0.so.0 + 0x1171d)
                 #11 0x00007ff31daa798a g_signal_emit_valist (libgobject-2.0.so.0 + 0x2f98a)
                 #12 0x00007ff31daa7b00 g_signal_emit (libgobject-2.0.so.0 + 0x2fb00)
                 #13 0x00007ff31e7083ff n/a (libwnck-3.so.0 + 0x183ff)
                 #14 0x00007ff31df7bf6f n/a (libgtk-3.so.0 + 0x83f6f)
                 #15 0x00007ff31da8b052 g_closure_invoke (libgobject-2.0.so.0 + 0x13052)
                 #16 0x00007ff31dab39c5 n/a (libgobject-2.0.so.0 + 0x3b9c5)
                 #17 0x00007ff31daa6bcb g_signal_emit_valist (libgobject-2.0.so.0 + 0x2ebcb)
                 #18 0x00007ff31daa7b00 g_signal_emit (libgobject-2.0.so.0 + 0x2fb00)
                 #19 0x00007ff31e242a75 n/a (libgtk-3.so.0 + 0x34aa75)
                 #20 0x00007ff31e0dc019 gtk_main_do_event (libgtk-3.so.0 + 0x1e4019)
                 #21 0x00007ff31de34413 n/a (libgdk-3.so.0 + 0x3c413)
                 #22 0x00007ff31de84e54 n/a (libgdk-3.so.0 + 0x8ce54)
                 #23 0x00007ff31d9928f4 g_main_context_dispatch (libglib-2.0.so.0 + 0x528f4)
                 #24 0x00007ff31d9e6821 n/a (libglib-2.0.so.0 + 0xa6821)
                 #25 0x00007ff31d991e43 g_main_loop_run (libglib-2.0.so.0 + 0x51e43)
                 #26 0x00007ff31e0d94ff gtk_main (libgtk-3.so.0 + 0x1e14ff)
                 #27 0x00007ff31e740b1b n/a (libmate-panel-applet-4.so.1 + 0x8b1b)
                 #28 0x000055a33aaff15f n/a (wnck-applet + 0x615f)
                 #29 0x00007ff31d798152 __libc_start_main (libc.so.6 + 0x28152)
                 #30 0x000055a33aaff1ce n/a (wnck-applet + 0x61ce)
                 
                 Stack trace of thread 7766:
                 #0  0x00007ff31d86546f __poll (libc.so.6 + 0xf546f)
                 #1  0x00007ff31d9e67af n/a (libglib-2.0.so.0 + 0xa67af)
                 #2  0x00007ff31d991121 g_main_context_iteration (libglib-2.0.so.0 + 0x51121)
                 #3  0x00007ff31a93dc0e n/a (libdconfsettings.so + 0x5c0e)
                 #4  0x00007ff31d9bfd31 n/a (libglib-2.0.so.0 + 0x7fd31)
                 #5  0x00007ff31d0013e9 start_thread (libpthread.so.0 + 0x93e9)
                 #6  0x00007ff31d870293 __clone (libc.so.6 + 0x100293)
                 
                 Stack trace of thread 7721:
                 #0  0x00007ff31d86546f __poll (libc.so.6 + 0xf546f)
                 #1  0x00007ff31d9e67af n/a (libglib-2.0.so.0 + 0xa67af)
                 #2  0x00007ff31d991e43 g_main_loop_run (libglib-2.0.so.0 + 0x51e43)
                 #3  0x00007ff31dbd1fe8 n/a (libgio-2.0.so.0 + 0x101fe8)
                 #4  0x00007ff31d9bfd31 n/a (libglib-2.0.so.0 + 0x7fd31)
                 #5  0x00007ff31d0013e9 start_thread (libpthread.so.0 + 0x93e9)
                 #6  0x00007ff31d870293 __clone (libc.so.6 + 0x100293)
                 
                 Stack trace of thread 7718:
                 #0  0x00007ff31d86546f __poll (libc.so.6 + 0xf546f)
                 #1  0x00007ff31d9e67af n/a (libglib-2.0.so.0 + 0xa67af)
                 #2  0x00007ff31d991121 g_main_context_iteration (libglib-2.0.so.0 + 0x51121)
                 #3  0x00007ff31d991172 n/a (libglib-2.0.so.0 + 0x51172)
                 #4  0x00007ff31d9bfd31 n/a (libglib-2.0.so.0 + 0x7fd31)
                 #5  0x00007ff31d0013e9 start_thread (libpthread.so.0 + 0x93e9)
                 #6  0x00007ff31d870293 __clone (libc.so.6 + 0x100293)
Dec 02 16:11:36 Hannah systemd[1]: systemd-coredump@15-9133-0.service: Succeeded.
Dec 02 16:11:36 Hannah audit[1]: SERVICE_STOP pid=1 uid=0 auid=4294967295 ses=4294967295 msg='unit=systemd-coredump@15-9133-0 comm="systemd" exe="/usr/lib/systemd/systemd" hostname=? addr=? terminal=? res=success'
Dec 02 16:11:36 Hannah mate-session[7590]: DEBUG(+): GsmDBusClient: obj_path=/org/freedesktop/DBus interface=org.freedesktop.DBus method=NameOwnerChanged
Dec 02 16:11:36 Hannah mate-session[7590]: DEBUG(+): GsmDBusClient: obj_path=/org/freedesktop/DBus interface=org.freedesktop.DBus method=NameOwnerChanged
Dec 02 16:11:36 Hannah mate-session[7590]: DEBUG(+): GsmDBusClient: obj_path=/org/freedesktop/DBus interface=org.freedesktop.DBus method=NameOwnerChanged
Dec 02 16:11:36 Hannah mate-session[7590]: DEBUG(+): GsmDBusClient: obj_path=/org/freedesktop/DBus interface=org.freedesktop.DBus method=NameOwnerChanged
Dec 02 16:11:36 Hannah mate-session[7590]: DEBUG(+): GsmDBusClient: obj_path=/org/freedesktop/DBus interface=org.freedesktop.DBus method=NameOwnerChanged
Dec 02 16:11:36 Hannah mate-session[7590]: DEBUG(+): GsmDBusClient: obj_path=/org/freedesktop/DBus interface=org.freedesktop.DBus method=NameOwnerChanged
Dec 02 16:11:36 Hannah mate-session[7590]: DEBUG(+): GsmDBusClient: obj_path=/org/freedesktop/DBus interface=org.freedesktop.DBus method=NameOwnerChanged
Dec 02 16:11:36 Hannah mate-session[7590]: DEBUG(+): GsmDBusClient: obj_path=/org/freedesktop/DBus interface=org.freedesktop.DBus method=NameOwnerChanged
Dec 02 16:11:36 Hannah mate-session[7590]: DEBUG(+): GsmDBusClient: obj_path=/org/freedesktop/DBus interface=org.freedesktop.DBus method=NameOwnerChanged
Dec 02 16:11:36 Hannah mate-session[7590]: DEBUG(+): GsmDBusClient: obj_path=/org/freedesktop/DBus interface=org.freedesktop.DBus method=NameOwnerChanged
Dec 02 16:11:36 Hannah audit[8937]: NETFILTER_CFG table=filter family=7 entries=0 op=xt_register pid=8937 comm=495043204C61756E6368
Dec 02 16:11:36 Hannah audit[153]: NETFILTER_CFG table=filter family=7 entries=0 op=xt_unregister pid=153 comm="kworker/u16:4"
Dec 02 16:11:36 Hannah audit: BPF prog-id=59 op=UNLOAD
Dec 02 16:11:36 Hannah audit: BPF prog-id=58 op=UNLOAD
Dec 02 16:11:36 Hannah rtkit-daemon[898]: Supervising 8 threads of 2 processes of 1 users.
Dec 02 16:11:36 Hannah rtkit-daemon[898]: Supervising 8 threads of 2 processes of 1 users.
Dec 02 16:11:42 Hannah dbus-daemon[7536]: [session uid=1000 pid=7536] Activating service name='org.mate.panel.applet.WnckletFactory' requested by ':1.22' (uid=1000 pid=7686 comm="mate-panel ")
Dec 02 16:11:42 Hannah mate-session[7590]: DEBUG(+): GsmDBusClient: obj_path=/org/freedesktop/DBus interface=org.freedesktop.DBus method=NameOwnerChanged
Dec 02 16:11:42 Hannah mate-session[7590]: DEBUG(+): GsmDBusClient: obj_path=/org/freedesktop/DBus interface=org.freedesktop.DBus method=NameOwnerChanged
Dec 02 16:11:42 Hannah mate-session[7590]: DEBUG(+): GsmDBusClient: obj_path=/org/freedesktop/DBus interface=org.freedesktop.DBus method=NameOwnerChanged
Dec 02 16:11:42 Hannah mate-session[7590]: DEBUG(+): GsmDBusClient: obj_path=/org/freedesktop/DBus interface=org.freedesktop.DBus method=NameOwnerChanged
Dec 02 16:11:42 Hannah mate-session[7590]: DEBUG(+): GsmDBusClient: obj_path=/org/freedesktop/DBus interface=org.freedesktop.DBus method=NameOwnerChanged
Dec 02 16:11:42 Hannah dbus-daemon[7536]: [session uid=1000 pid=7536] Successfully activated service 'org.mate.panel.applet.WnckletFactory'
Dec 02 16:11:42 Hannah mate-session[7590]: DEBUG(+): GsmDBusClient: obj_path=/org/freedesktop/DBus interface=org.freedesktop.DBus method=NameOwnerChanged
Dec 02 16:11:42 Hannah mate-session[7590]: DEBUG(+): GsmDBusClient: obj_path=/org/freedesktop/DBus interface=org.freedesktop.DBus method=NameOwnerChanged
Dec 02 16:11:42 Hannah mate-session[7590]: DEBUG(+): GsmDBusClient: obj_path=/org/freedesktop/DBus interface=org.freedesktop.DBus method=NameOwnerChanged
Dec 02 16:11:42 Hannah mate-session[7590]: DEBUG(+): GsmDBusClient: obj_path=/org/freedesktop/DBus interface=org.freedesktop.DBus method=NameOwnerChanged
Dec 02 16:11:42 Hannah mate-session[7590]: DEBUG(+): GsmDBusClient: obj_path=/org/freedesktop/DBus interface=org.freedesktop.DBus method=NameOwnerChanged
Dec 02 16:11:44 Hannah audit[7288]: NETFILTER_CFG table=filter family=7 entries=0 op=xt_unregister pid=7288 comm="kworker/u16:0"
Dec 02 16:11:44 Hannah kernel: kauditd_printk_skb: 5 callbacks suppressed
Dec 02 16:11:44 Hannah kernel: audit: type=1325 audit(1606954304.975:362): table=filter family=7 entries=0 op=xt_unregister pid=7288 comm="kworker/u16:0"
```

### PR DESCRIPTION
**Pull request by vkareh**
This allows thumbnail previews to be properly rendered on HiDPI displays
and ensures that the window surface is flushed before painting it.

Fixes #1166

### CODE REVIEW

**Review by lukefromdc — APPROVED** [review]
Builds and runs fine,didn't put any runtime errors in ~/.xsession-errors 
Tested with a 4K monitor and oh yeah this makes much sharper window previews, this basic change is tried and true for dealing with hidpi. I don't have the problematic  cairo 1.17 to test against (we have 1.16 in Debian Unstable right now) so I cannot evaluate whether it fixes that crash, but this sure as hell makes nicer previews with 4K

**Comment by lukefromdc** [comment]
I built a .deb of this rebased against today's master, so it's my day to day panel for now, working well

**Review by rbuj — COMMENTED** [review]
A segment violation is still occurring. Test:
```
$ git clone https://github.com/freedesktop/cairo.git
$ cd cairo
$ git log -1 --pretty=%h
f7054c892
$ ./autogen.sh --prefix=/usr --enable-xlib-xcb && make &> /dev/null && sudo make install &> /dev/null
<cut>
cairo (version 1.17.3 [git]) will be compiled with:

The following surface backends:
  Image:         yes (always builtin)
  Recording:     yes (always builtin)
  Observer:      yes (always builtin)
  Mime:          yes (always builtin)
  Tee:           no (disabled, use --enable-tee to enable)
  XML:           no (disabled, use --enable-xml to enable)
  Xlib:          yes
  Xlib Xrender:  yes
  Qt:            no (disabled, use --enable-qt to enable)
  Quartz:        no (requires CoreGraphics framework)
  Quartz-image:  no (disabled, use --enable-quartz-image to enable)
  XCB:           yes
  Win32:         no (requires a Win32 platform)
  OS2:           no (disabled, use --enable-os2 to enable)
  CairoScript:   yes
  PostScript:    yes
  PDF:           yes
  SVG:           yes
  OpenGL:        no (disabled, use --enable-gl to enable)
  OpenGL ES 2.0: no (disabled, use --enable-glesv2 to enable)
  OpenGL ES 3.0: no (disabled, use --enable-glesv3 to enable)
  BeOS:          no (disabled, use --enable-beos to enable)
  DirectFB:      no (disabled, use --enable-directfb to enable)
  OpenVG:        no (disabled, use --enable-vg to enable)
  DRM:           no (disabled, use --enable-drm to enable)
  Cogl:          no (disabled, use --enable-cogl to enable)

The following font backends:
  User:          yes (always builtin)
  FreeType:      yes
  Fontconfig:    yes
  Win32:         no (requires a Win32 platform)
  Quartz:        no (requires CoreGraphics framework)

The following functions:
  PNG functions:   yes
  GLX functions:   no (not required by any backend)
  WGL functions:   no (not required by any backend)
  EGL functions:   no (not required by any backend)
  X11-xcb functions: yes
  XCB-shm functions: yes

The following features and utilities:
  cairo-trace:                yes
  cairo-script-interpreter:   yes

And the following internal features:
  pthread:       yes
  gtk-doc:       no
  gcov support:  no
  symbol-lookup: no (requires bfd)
  test surfaces: no (disabled, use --enable-test-surfaces to enable)
  ps testing:    yes
  pdf testing:   yes
  svg testing:   yes


--- The Xlib/XCB functions feature is still under active development and is
--- included in this release only as a preview. It does NOT fully work yet
--- and incompatible changes may yet be made to Xlib/XCB functions specific
--- API.
```
```
$ git clone https://github.com/mate-desktop/mate-panel.git
$ cd mate-panel
$ git checkout cairo-thumbnail-previews
$ ./autogen.sh --prefix=/usr && make &> /dev/null && sudo make install &> /dev/null
<cut>

              mate-panel 1.25.1
              =================

        prefix:                        /usr
        exec_prefix:                   ${prefix}
        libdir:                        ${exec_prefix}/lib64
        bindir:                        ${exec_prefix}/bin
        sbindir:                       ${exec_prefix}/sbin
        sysconfdir:                    /etc
        localstatedir:                 /var
        datadir:                       ${datarootdir}
        source code location:          .
        compiler:                      gcc
        cflags:                        
        warning flags:                 -Wall -Wmissing-prototypes
        Maintainer mode:               yes
        Use *_DISABLE_DEPRECATED:      no
        Applets to build in-process:   (none)
        Wayland support:               yes
        X11 support:                   yes
        XRandr support:                yes
        Build introspection support:   yes
        Build gtk-doc documentation:   no


Now type `make' to compile mate-panel

```
```
Dec 05 23:39:37 localhost.localdomain systemd-coredump[147815]: [LNK] Process 147360 (wnck-applet) of user 1000 dumped core.
                                                                
                                                                Stack trace of thread 147360:
                                                                #0  0x00007fdde78629d5 raise (libc.so.6 + 0x3d9d5)
                                                                #1  0x00007fdde784b8a4 abort (libc.so.6 + 0x268a4)
                                                                #2  0x00007fdde784b789 __assert_fail_base.cold (libc.so.6 + 0x26789)
                                                                #3  0x00007fdde785b026 __assert_fail (libc.so.6 + 0x36026)
                                                                #4  0x00007fdde835ccb1 INT_cairo_surface_mark_dirty_rectangle (libcairo.so.2 + 0x6fcb1)
                                                                #5  0x00007fdde837e830 _cairo_xlib_xcb_surface_mark_dirty (libcairo.so.2 + 0x91830)
                                                                #6  0x00007fdde835cc09 INT_cairo_surface_mark_dirty_rectangle (libcairo.so.2 + 0x6fc09)
                                                                #7  0x00007fdde835e1c5 INT_cairo_surface_mark_dirty (libcairo.so.2 + 0x711c5)
                                                                #8  0x0000000000408943 preview_window_thumbnail (wnck-applet + 0x8943)
                                                                #9  0x0000000000408dac applet_enter_notify_event (wnck-applet + 0x8dac)
                                                                #10 0x00007fdde7b7a4a1 g_cclosure_marshal_VOID__POINTERv (libgobject-2.0.so.0 + 0x124a1)
                                                                #11 0x00007fdde7b99080 g_signal_emit_valist (libgobject-2.0.so.0 + 0x31080)
                                                                #12 0x00007fdde7b991a3 g_signal_emit (libgobject-2.0.so.0 + 0x311a3)
                                                                #13 0x00007fdde8ea18d0 wnck_task_enter_notify_event (libwnck-3.so.0 + 0x1e8d0)
                                                                #14 0x00007fdde8a3c59b _gtk_marshal_BOOLEAN__BOXED (libgtk-3.so.0 + 0x3de59b)
                                                                #15 0x00007fdde7b7be2a g_closure_invoke (libgobject-2.0.so.0 + 0x13e2a)
                                                                #16 0x00007fdde7ba5273 signal_emit_unlocked_R.isra.0 (libgobject-2.0.so.0 + 0x3d273)
                                                                #17 0x00007fdde7b98aee g_signal_emit_valist (libgobject-2.0.so.0 + 0x30aee)
                                                                #18 0x00007fdde7b991a3 g_signal_emit (libgobject-2.0.so.0 + 0x311a3)
                                                                #19 0x00007fdde8a03184 gtk_widget_event_internal.part.0.lto_priv.0 (libgtk-3.so.0 + 0x3a5184)
                                                                #20 0x00007fdde88a67b7 gtk_main_do_event (libgtk-3.so.0 + 0x2487b7)
                                                                #21 0x00007fdde8595043 _gdk_event_emit (libgdk-3.so.0 + 0x35043)
                                                                #22 0x00007fdde85cbfc2 gdk_event_source_dispatch (libgdk-3.so.0 + 0x6bfc2)
                                                                #23 0x00007fdde7a8a7ef g_main_context_dispatch (libglib-2.0.so.0 + 0x537ef)
                                                                #24 0x00007fdde7adc5d8 g_main_context_iterate.constprop.0 (libglib-2.0.so.0 + 0xa55d8)
                                                                #25 0x00007fdde7a89eb3 g_main_loop_run (libglib-2.0.so.0 + 0x52eb3)
                                                                #26 0x00007fdde88a220d gtk_main (libgtk-3.so.0 + 0x24420d)
                                                                #27 0x00007fdde8ed4a54 _mate_panel_applet_factory_main_internal (libmate-panel-applet-4.so.1 + 0xca54)
                                                                #28 0x00007fdde8ed4aa9 mate_panel_applet_factory_main (libmate-panel-applet-4.so.1 + 0xcaa9)
                                                                #29 0x00000000004079de main (wnck-applet + 0x79de)
                                                                #30 0x00007fdde784d1e2 __libc_start_main (libc.so.6 + 0x281e2)
                                                                #31 0x000000000040725e _start (wnck-applet + 0x725e)
                                                                
                                                                Stack trace of thread 147366:
                                                                #0  0x00007fdde791b80f __poll (libc.so.6 + 0xf680f)
                                                                #1  0x00007fdde7adc576 g_main_context_iterate.constprop.0 (libglib-2.0.so.0 + 0xa5576)
                                                                #2  0x00007fdde7a87bc3 g_main_context_iteration (libglib-2.0.so.0 + 0x50bc3)
                                                                #3  0x00007fdde7a897e1 glib_worker_main (libglib-2.0.so.0 + 0x527e1)
                                                                #4  0x00007fdde7ab8132 g_thread_proxy (libglib-2.0.so.0 + 0x81132)
                                                                #5  0x00007fdde82d43f9 start_thread (libpthread.so.0 + 0x93f9)
                                                                #6  0x00007fdde7926903 __clone (libc.so.6 + 0x101903)
                                                                
                                                                Stack trace of thread 147367:
                                                                #0  0x00007fdde792130d syscall (libc.so.6 + 0xfc30d)
                                                                #1  0x00007fdde7ad716c g_cond_wait_until (libglib-2.0.so.0 + 0xa016c)
                                                                #2  0x00007fdde7a5b381 g_async_queue_pop_intern_unlocked (libglib-2.0.so.0 + 0x24381)
                                                                #3  0x00007fdde7a5b506 g_async_queue_timeout_pop (libglib-2.0.so.0 + 0x24506)
                                                                #4  0x00007fdde7abad79 g_thread_pool_thread_proxy.lto_priv.0 (libglib-2.0.so.0 + 0x83d79)
                                                                #5  0x00007fdde7ab8132 g_thread_proxy (libglib-2.0.so.0 + 0x81132)
                                                                #6  0x00007fdde82d43f9 start_thread (libpthread.so.0 + 0x93f9)
                                                                #7  0x00007fdde7926903 __clone (libc.so.6 + 0x101903)
                                                                
                                                                Stack trace of thread 147368:
                                                                #0  0x00007fdde791b80f __poll (libc.so.6 + 0xf680f)
                                                                #1  0x00007fdde7adc576 g_main_context_iterate.constprop.0 (libglib-2.0.so.0 + 0xa5576)
                                                                #2  0x00007fdde7a89eb3 g_main_loop_run (libglib-2.0.so.0 + 0x52eb3)
                                                                #3  0x00007fdde7cd1d1a gdbus_shared_thread_func.lto_priv.0 (libgio-2.0.so.0 + 0x10fd1a)
                                                                #4  0x00007fdde7ab8132 g_thread_proxy (libglib-2.0.so.0 + 0x81132)
                                                                #5  0x00007fdde82d43f9 start_thread (libpthread.so.0 + 0x93f9)
                                                                #6  0x00007fdde7926903 __clone (libc.so.6 + 0x101903)
                                                                
                                                                Stack trace of thread 147501:
                                                                #0  0x00007fdde791b80f __poll (libc.so.6 + 0xf680f)
                                                                #1  0x00007fdde7adc576 g_main_context_iterate.constprop.0 (libglib-2.0.so.0 + 0xa5576)
                                                                #2  0x00007fdde7a87bc3 g_main_context_iteration (libglib-2.0.so.0 + 0x50bc3)
                                                                #3  0x00007fdde8ee664d dconf_gdbus_worker_thread (libdconfsettings.so + 0x664d)
                                                                #4  0x00007fdde7ab8132 g_thread_proxy (libglib-2.0.so.0 + 0x81132)
                                                                #5  0x00007fdde82d43f9 start_thread (libpthread.so.0 + 0x93f9)
                                                                #6  0x00007fdde7926903 __clone (libc.so.6 + 0x101903)
```
Edit: gdb bt
```
(gdb) 
#0  0x00007fe6b6e939d5 in raise () at /lib64/libc.so.6
#1  0x00007fe6b6e7c8a4 in abort () at /lib64/libc.so.6
#2  0x00007fe6b6e7c789 in _nl_load_domain.cold () at /lib64/libc.so.6
#3  0x00007fe6b6e8c026 in annobin_assert.c_end () at /lib64/libc.so.6
#4  0x00007fe6b79b6f89 in INT_cairo_surface_mark_dirty_rectangle (surface=0x125db70, x=0, y=0, width=1812, height=1125) at cairo-surface.c:1733
#5  0x00007fe6b79e6e23 in _cairo_xlib_xcb_surface_mark_dirty (abstract_surface=0x1222150, x=0, y=0, width=1812, height=1125) at cairo-xlib-xcb-surface.c:265
#6  0x00007fe6b79b7093 in INT_cairo_surface_mark_dirty_rectangle (surface=0x1222150, x=0, y=0, width=1812, height=1125) at cairo-surface.c:1756
#7  0x00007fe6b79b6ed0 in INT_cairo_surface_mark_dirty (surface=0x1222150) at cairo-surface.c:1687
#8  0x0000000000408943 in preview_window_thumbnail (wnck_window=0x11987c0, tasklist=0x10e2400) at window-list.c:275
#9  0x0000000000408dac in applet_enter_notify_event (tl=0x118c320, wnck_windows=0xffe080 = {...}, tasklist=0x10e2400) at window-list.c:400
#10 0x00007fe6b71ab4a1 in g_cclosure_marshal_VOID__POINTERv () at /lib64/libgobject-2.0.so.0
#11 0x00007fe6b71ca080 in g_signal_emit_valist () at /lib64/libgobject-2.0.so.0
#12 0x00007fe6b71ca1a3 in g_signal_emit () at /lib64/libgobject-2.0.so.0
#13 0x00007fe6b85258d0 in wnck_task_enter_notify_event () at /lib64/libwnck-3.so.0
#14 0x00007fe6b80c059b in _gtk_marshal_BOOLEAN__BOXED () at /lib64/libgtk-3.so.0
#15 0x00007fe6b71ace2a in g_closure_invoke () at /lib64/libgobject-2.0.so.0
#16 0x00007fe6b71d6273 in signal_emit_unlocked_R.isra.0 () at /lib64/libgobject-2.0.so.0
#17 0x00007fe6b71c9aee in g_signal_emit_valist () at /lib64/libgobject-2.0.so.0
#18 0x00007fe6b71ca1a3 in g_signal_emit () at /lib64/libgobject-2.0.so.0
#19 0x00007fe6b8087184 in gtk_widget_event_internal.part.0.lto_priv () at /lib64/libgtk-3.so.0
#20 0x00007fe6b7f2a7b7 in gtk_main_do_event () at /lib64/libgtk-3.so.0
#21 0x00007fe6b7c19043 in _gdk_event_emit () at /lib64/libgdk-3.so.0
#22 0x00007fe6b7c4ffc2 in gdk_event_source_dispatch () at /lib64/libgdk-3.so.0
#23 0x00007fe6b70bb7ef in g_main_context_dispatch () at /lib64/libglib-2.0.so.0
#24 0x00007fe6b710d5d8 in g_main_context_iterate.constprop () at /lib64/libglib-2.0.so.0
#25 0x00007fe6b70baeb3 in g_main_loop_run () at /lib64/libglib-2.0.so.0
#26 0x00007fe6b7f2620d in gtk_main () at /lib64/libgtk-3.so.0
#27 0x00007fe6b8558a54 in _mate_panel_applet_factory_main_internal (factory_id=0x410171 "WnckletFactory", out_process=1, applet_type=, callback=0x40776c <wncklet_factory>, user_data=0x0) at mate-panel-applet.c:2344
#28 0x00007fe6b8558aa9 in mate_panel_applet_factory_main (factory_id=0x410171 "WnckletFactory", out_process=1, applet_type=, callback=0x40776c <wncklet_factory>, user_data=0x0) at mate-panel-applet.c:2372
#29 0x00000000004079de in main (argc=1, argv=0x7ffc06acfda8) at wncklet.c:155
```

**Comment by lukefromdc** [comment]
I don't have cairo 1.17 here, so can't work on that part of the problem

**Comment by lukefromdc** [comment]
OK, we now have a report 
https://github.com/mate-desktop/mate-panel/issues/1166#issuecomment-739626933
that a new cairo version (1.17.4-2) fixes the crash with cairo 1.17 in Arch. We also know this PR gives much better thumbnail rendering in Hidpi.  This should also be tested with cairo 1.17.4-2 but if it passes that should be ready to go unless someone else finds a new problem

File: applets/wncklet/window-list.c [hunk 1]
```diff
@@ -255,50 +257,71 @@ static GdkPixbuf *preview_window_thumbnail (WnckWindow *wnck_window, TasklistDat
...
 	/* Scale to configured size while maintaining aspect ratio */
 	if (width > height)
 	{
-		ratio = (double) height / (double) width;
-		width = MIN(width, tasklist->thumbnail_size);
-		height = width * ratio;
+		int max_size = MIN(width, tasklist->thumbnail_size);
+		ratio = (double) width / (double) max_size;
+		width = max_size;
+		height = (int) ((double) height / ratio);
```
Comment (rbuj) [inline applets/wncklet/window-list.c:289]: The ratio is usually within the range 0..1, which can be achieved by exchanging the numerator and denominator and multiplying the smaller of the two by the ratio later. In addition, the computational cost of a floating-point division is usually higher than a multiplication.

Comment (rbuj) [reply applets/wncklet/window-list.c:289]:
```diff
diff --git a/applets/wncklet/window-list.c b/applets/wncklet/window-list.c
index bb910f20..fdfa72a8 100644
--- a/applets/wncklet/window-list.c
+++ b/applets/wncklet/window-list.c
@@ -283,17 +283,17 @@ static cairo_surface_t *preview_window_thumbnail (WnckWindow *wnck_window, Taskl
        /* Scale to configured size while maintaining aspect ratio */
        if (width > height)
        {
-               int max_size = MIN(width, tasklist->thumbnail_size);
-               ratio = (double) width / (double) max_size;
+               int max_size = MIN (width, tasklist->thumbnail_size);
+               ratio = (double) max_size / (double) width;
                width = max_size;
-               height = (int) ((double) height / ratio);
+               height = (int) ((double) height * ratio);
        }
        else
        {
-               int max_size = MIN(height, tasklist->thumbnail_size);
-               ratio = (double) height / (double) max_size;
+               int max_size = MIN (height, tasklist->thumbnail_size);
+               ratio = (double) max_size / (double) height;
                height = max_size;
-               width = (int) ((double) width / ratio);
+               width = (int) ((double) width * ratio);
        }
 
        thumbnail = cairo_surface_create_similar (screenshot,
@@ -301,7 +301,7 @@ static cairo_surface_t *preview_window_thumbnail (WnckWindow *wnck_window, Taskl
                                                  width, height);
 
        cr = cairo_create (thumbnail);
-       cairo_scale (cr, scale/ratio, scale/ratio);
+       cairo_scale (cr, scale * ratio, scale * ratio);
        cairo_set_source_surface (cr, screenshot, 0, 0);
        cairo_paint (cr);
 
```

File: applets/wncklet/window-list.c [hunk 2]
```diff
@@ -237,16 +237,18 @@ static void applet_change_background(MatePanelApplet* applet, MatePanelAppletBac
...
+	cairo_surface_t *thumbnail;
+	cairo_t *cr;
 	double ratio;
-	int width, height;
-	int scale;
+	int width, height, scale;
 
-	window = gdk_x11_window_foreign_new_for_display (gdk_display_get_default (), wnck_window_get_xid (wnck_window));
+	display = gdk_display_get_default ();
+	window = gdk_x11_window_foreign_new_for_display (display, wnck_window_get_xid (wnck_window));
```
Comment (rbuj) [inline applets/wncklet/window-list.c:251]: There is need to add a new display variable called display.

File: applets/wncklet/window-list.c [hunk 3]
```diff
@@ -255,50 +257,71 @@ static GdkPixbuf *preview_window_thumbnail (WnckWindow *wnck_window, TasklistDat
...
 {
 	GdkMonitor *monitor;
 	GdkRectangle monitor_geom;
 	int x_pos, y_pos;
-	int width, height;
+	int width, height, scale;
 
-	width = gdk_pixbuf_get_width (thumbnail);
-	height = gdk_pixbuf_get_height (thumbnail);
+	scale = gtk_widget_get_scale_factor (tasklist->preview);
```
Comment (rbuj) [inline applets/wncklet/window-list.c:322]: What happens if the scale of the thumbnail is different from its placement?

File: applets/wncklet/window-list.c (hunk 1 above)
Comment (vkareh) [reply applets/wncklet/window-list.c]: Thanks, good catch :+1:

File: applets/wncklet/window-list.c (hunk 2 above)
Comment (vkareh) [reply applets/wncklet/window-list.c]: it's there. But realized that this change is not really needed, so I removed it

File: applets/wncklet/window-list.c (hunk 3 above)
Comment (vkareh) [reply applets/wncklet/window-list.c:320]: not sure I understand the question. Scale is based on the dpi multiplier (1 for regular, 2 for HiDPI, etc). The width/height are used to resize the thumbnail correctly, but the positioning is done based on the mouse coordinates. Without the scale, in a HiDPI environment, the thumbnail will end up being a large widget with a small surface in its corner.

**Review by lukefromdc — APPROVED** [review]
Again I got good results with the latest version of this PR with a 4K monitor and cairo 1.16

File: applets/wncklet/window-list.c (hunk 3 above)
Comment (rbuj) [reply applets/wncklet/window-list.c:320]: In this example we have two screens: The main screen is not HiDPI so it has a 1:1 scale. The second screen is HiDPI and it has a 2:1 scale. The window thumbnails of the second screen will have twice the normal size if they are displayed on the main screen.

Comment (rbuj) [reply applets/wncklet/window-list.c:320]: If the scale has the same value for all screens, you could set its value within the function `applet_enter_notify_event`, and call the two functions (`preview_window_thumbnail` and `preview_window_reposition`) adding this new argument.

Comment (rbuj) [reply applets/wncklet/window-list.c:320]:
```C
diff --git a/applets/wncklet/window-list.c b/applets/wncklet/window-list.c
index 4708d56c..a456bac2 100644
--- a/applets/wncklet/window-list.c
+++ b/applets/wncklet/window-list.c
@@ -237,7 +237,7 @@ static void applet_change_background(MatePanelApplet* applet, MatePanelAppletBac
 
 #ifdef HAVE_X11
 #ifdef HAVE_WINDOW_PREVIEWS
-static cairo_surface_t *preview_window_thumbnail (WnckWindow *wnck_window, TasklistData *tasklist)
+static cairo_surface_t *preview_window_thumbnail (WnckWindow *wnck_window, TasklistData *tasklist, int *thumbnail_width, int *thumbnail_height, int *thumbnail_scale)
 {
        GdkWindow *window;
        cairo_surface_t *screenshot;
@@ -306,20 +306,19 @@ static cairo_surface_t *preview_window_thumbnail (WnckWindow *wnck_window, Taskl
        cairo_destroy (cr);
        cairo_surface_destroy (screenshot);
 
+       *thumbnail_width = width;
+       *thumbnail_height = height;
+       *thumbnail_scale = scale;
+
        return thumbnail;
 }
 
 #define PREVIEW_PADDING 5
-static void preview_window_reposition (TasklistData *tasklist, cairo_surface_t *thumbnail)
+static void preview_window_reposition (TasklistData *tasklist, cairo_surface_t *thumbnail, int width, int height)
 {
        GdkMonitor *monitor;
        GdkRectangle monitor_geom;
        int x_pos, y_pos;
-       int width, height, scale;
-
-       scale = gtk_widget_get_scale_factor (tasklist->preview);
-       width = cairo_image_surface_get_width (thumbnail) / scale;
-       height = cairo_image_surface_get_height (thumbnail) / scale;
 
        /* Resize window to fit thumbnail */
        gtk_window_resize (GTK_WINDOW (tasklist->preview), width, height);
@@ -368,6 +367,9 @@ static gboolean applet_enter_notify_event (WnckTasklist *tl, GList *wnck_windows
        cairo_surface_t *thumbnail;
        WnckWindow *wnck_window = NULL;
        int n_windows;
+       int thumbnail_width;
+       int thumbnail_height;
+       int thumbnail_scale;
 
        if (tasklist->preview != NULL)
        {
@@ -395,7 +397,7 @@ static gboolean applet_enter_notify_event (WnckTasklist *tl, GList *wnck_windows
                                                  wnck_screen_get_active_workspace (wnck_screen_get_default ())))
                return FALSE;
 
-       thumbnail = preview_window_thumbnail (wnck_window, tasklist);
+       thumbnail = preview_window_thumbnail (wnck_window, tasklist, &thumbnail_width, &thumbnail_height, &thumbnail_scale);
 
        if (thumbnail == NULL)
                return FALSE;
@@ -406,7 +408,7 @@ static gboolean applet_enter_notify_event (WnckTasklist *tl, GList *wnck_windows
        gtk_widget_set_app_paintable (tasklist->preview, TRUE);
        gtk_window_set_resizable (GTK_WINDOW (tasklist->preview), TRUE);
 
-       preview_window_reposition (tasklist, thumbnail);
+       preview_window_reposition (tasklist, thumbnail, thumbnail_width/thumbnail_scale, thumbnail_height/thumbnail_scale);
 
        gtk_widget_show (tasklist->preview);
 
```

**Review by rbuj — APPROVED** [review]
test: save thumbnail in home folder (HiDPI 2: `gsettings set org.mate.interface window-scaling-factor 2`)
```
$ file thumbnail-*.png
thumbnail-master.png: PNG image data, 200 x 132, 8-bit/color RGBA, non-interlaced
thumbnail-pr.png:     PNG image data, 400 x 264, 8-bit/color RGB, non-interlaced
```
### master
```diff
diff --git a/applets/wncklet/window-list.c b/applets/wncklet/window-list.c
index 6038400e..e211047e 100644
--- a/applets/wncklet/window-list.c
+++ b/applets/wncklet/window-list.c
@@ -338,6 +338,11 @@ static gboolean preview_window_draw (GtkWidget *widget, cairo_t *cr, GdkPixbuf *
 
        context = gtk_widget_get_style_context (widget);
        gtk_render_icon (context, cr, thumbnail, 0, 0);
+#if 1
+       gchar *filename = g_build_filename (g_get_home_dir (), "thumbnail.png", NULL);
+       gdk_pixbuf_save (thumbnail, filename, "png", NULL, NULL);
+       g_free (filename);
+#endif
 
        return FALSE;
 }
```
### pr
```diff
diff --git a/applets/wncklet/window-list.c b/applets/wncklet/window-list.c
index 4708d56c..be632dce 100644
--- a/applets/wncklet/window-list.c
+++ b/applets/wncklet/window-list.c
@@ -359,6 +359,11 @@ static gboolean preview_window_draw (GtkWidget *widget, cairo_t *cr, cairo_surfa
 
        context = gtk_widget_get_style_context (widget);
        gtk_render_icon_surface (context, cr, thumbnail, 0, 0);
+#if 1
+       gchar *filename = g_build_filename (g_get_home_dir (), "thumbnail.png", NULL);
+       cairo_surface_write_to_png (thumbnail, filename);
+       g_free (filename);
+#endif
 
        return FALSE;
 }
```
### master
thumbnail-master
### pr
thumbnail-pr

File: applets/wncklet/window-list.c (hunk 3 above)
Comment (rbuj) [reply applets/wncklet/window-list.c:320]: It can be done in another commit.
